version: '3.8'
services:
  mysql:
    image: 'mysql:8.0'
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'laravel'
      MYSQL_DATABASE: 'betterhm_backend'
    volumes:
      - './mysql-data:/var/lib/mysql'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p laravel" ]
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:alpine'
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
