#name: Build and Publish docker images
#on: [ push ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Build image
#        run: make docker-build
#      - name: Login to GitHub container registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Publish image
#        run: make docker-push
#
